-- 1. Create the mapping table if it doesn't exist
CREATE TABLE IF NOT EXISTS "all_topics_with_main" (
    id bigint generated by default as identity primary key,
    topic text unique not null,
    main_topic text not null
);

-- 2. (Optional) Insert sample data - YOU NEED TO REPLACE THIS WITH YOUR ACTUAL MAPPING
-- INSERT INTO "all_topics_with_main" (topic, main_topic) VALUES
-- ('Wrong Network Payment', 'Payment Issue'),
-- ('Crypto Payment Issue', 'Payment Issue');

-- 3. Run the update again
UPDATE "Intercom Topic" t
SET "Main-Topics" = (
  SELECT jsonb_agg(DISTINCT m.main_topic)
  FROM jsonb_array_elements_text(t."Sub-Topics") AS elem
  JOIN "all_topics_with_main" m ON m.topic = elem
)
WHERE t."Sub-Topics" IS NOT NULL 
  AND jsonb_array_length(t."Sub-Topics") > 0;
