-- Find all Sub-Topics that are present in your data but MISSING from the mapping list
WITH UnmappedData AS (
    SELECT DISTINCT elem AS sub_topic
    FROM "Intercom Topic",
    jsonb_array_elements_text("Sub-Topics") AS elem
    WHERE "Sub-Topics" IS NOT NULL
)
SELECT sub_topic
FROM UnmappedData
WHERE sub_topic NOT IN (
    'Veriff Doesn''t Accept KYC Documents',
    'Waiting For KYC Verification',
    'KYC Verification Delay Issue',
    'KYC Done Yet to Receive FundedNext Account',
    'Eligible for KYC But Pop-Up Missing',
    'Already submitted but Dashboard shows “Verification Required”',
    'TRM Email Issue',
    'AI Interview / HireFlix Issue',
    'Live Interview – No One Joined',
    'Missed Interview Email',
    'Underage',
    'Swift KYC Not Eligible',
    'KYC Eligibility Inquiry',
    'Fundednext Account Query',
    'Did not receive Phase 2 Account',
    'Facing error while trying to sign agreement',
    'Challenge Account Query',
    'Unable to Create an Account',
    'Email already taken during registration',
    'Cannot update information',
    'Wrong Email Used',
    'Email Change',
    'Name Change',
    'Country Change',
    'Account Delete Request',
    'Missing account in breached/inactive section',
    'Account flagged without email',
    'Account Deactivation Due to Abusive Activities',
    'IP/Device Confirmation',
    'Dashboard update delay',
    'Dashboard Access Blocked (Client Internet)',
    'Dashboard Access Blocked (TT Issue)',
    'Account Breach Issue',
    '“Undefined” Login Error',
    'Login Technical Glitch',
    'MT5 Platform Login Issues',
    'MT4 Login Issue',
    'TradingView login Issue',
    'Tradovate login Issue',
    'Ninjatrader login issue',
    'Competition Login Issue',
    'Missing Password Mail',
    'Next Phase Button Missing',
    'Platform Freeze',
    'Price/Chart Discrepancy',
    'Market Data Delayed Issue',
    'Missing Old Chart Data',
    'Unable to Use Indicator',
    'Unable to Use EA',
    'TradingView not available for CFD',
    'Crypto Pair Unavailable',
    'Crypto Weekend Trading',
    'High Spread',
    'Unable to Close During News',
    'Off-Market Hour Issue',
    'Incorrect Trading Cycle',
    'Trading Disabled',
    'Not Enough Money',
    'Pending Order Didn''t Execute',
    'Trade Closed at Cycle End',
    'Trade Disappeared',
    'Unauthorized Trade',
    'TP Didn''t Hit Desired Price',
    'Trade Closed Outside Candle (News)',
    'Profit Target Reached but Minimum Trading Days Incomplete',
    'Minimum Trading Days Confusion',
    'Weekend Gap',
    'ASK/BID Confusion',
    '50 Trades Limit Exceeded',
    'Slippage Issue',
    'Regular Slippage',
    'Due to High Lot Size',
    'During News / High Impact',
    'Due to Server Issue',
    'Volume Surge',
    'Midnight Slippage',
    'Swap Charge Confusion',
    'High Processing Fee Complaint',
    'Affiliate Issue',
    'Affiliate Code Failed',
    'Payout On Hold',
    'Payout Delay Issue',
    'Not Eligible for Payout',
    'Payout Discrepancy',
    'Invalid Wallet',
    'RiseWorks Issue',
    'Unable to See Payout Proof',
    'Invoice Request',
    'TRM Deduction Email',
    'Payout from Breached Account',
    'Profit Share Below Minimum ($20)',
    'ECM Issue',
    'Claiming Brand Promise',
    'Payout Related Query',
    'Reported Late (3+ weeks)',
    'Elite Trader Certificate',
    'Payout Certificate',
    'Checking Elite Cert in Wrong Phase',
    'Certificate Name Issue',
    'Asking for Certificate After Phase 2',
    'Leaderboard Error',
    'Unhappy with Winner Result',
    'Breached Competition Rule',
    'Reward Delay',
    'Asking Winners Info',
    'Registered for Next Month',
    'Wants Competition Reset',
    'Competition Rule Clarification',
    'Unable to register in the Monthly Competition',
    'Restricted Country Issue',
    'Location Related Issue',
    'Concern about EA Rules',
    'EA Restriction (cTrader)',
    'Abuser Client (Banned)',
    'Leverage Reduction',
    'Verdict from CPM',
    'Verdict from Trading & Ethics',
    'Verdict from PO',
    '2FA Issue',
    'OTP Not Received',
    'Balance Mismatch',
    'Facing Payment Error',
    'Payment Method Not Available',
    'UPI Payment Missing',
    'Payment Rejected from Client’s End',
    'Partial Payment Not Possible',
    'No Payment Found (UPI/Local)',
    'Unable to Submit Payment Form (TC Pay)',
    'Account Not Provided Instantly (TC Pay)',
    'Account Not Provided Instantly (Local)',
    'Account Not Provided Instantly (Crypto)',
    'Paid Less Than Needed',
    'Crypto Payment Not Reflected',
    'Wrong Network Payment',
    'Network Not Available',
    'Crypto Payment Failed (Client Side)',
    'No Crypto Payment Found',
    'Double Charged',
    'Refund Delay',
    'Confirmo Refund Issue',
    'Coupon Code Not Working',
    'Coupon Not Available',
    'Forgot to Apply Coupon',
    'Looking for coupon code',
    'No Personal Coupon',
    'Unhappy with Coupon Perks',
    'Unsatisfied with Discount',
    'Offer Related Query',
    'Halloween Offer Query',
    'Offer related confusion',
    'Giveaway Claim',
    'Giveaway Query',
    'Unhappy Not Winning Giveaway',
    'Missing Free BOGO Account',
    'Asking for BOGO Early',
    'Delay in Receiving Customer Support.',
    'Subscription Email Issue',
    'Dispute Related Issue',
    'Other'
)
ORDER BY sub_topic;
