
// Helper for Topic Mapping (Extracted from SQL)
// Used to strictly filter sub-topics based on main topic selection
export const TOPIC_MAPPING = {
    "Veriff Doesn't Accept KYC Documents": "KYC_Issue",
    "Waiting For KYC Verification": "KYC_Issue",
    "KYC Verification Delay Issue": "KYC_Issue",
    "KYC Done Yet to Receive FundedNext Account": "KYC_Issue",
    "Eligible for KYC But Pop-Up Missing": "KYC_Issue",
    "Already submitted but Dashboard shows “Verification Required”": "KYC_Issue",
    "TRM Email Issue": "KYC_Issue",
    "AI Interview / HireFlix Issue": "KYC_Issue",
    "Live Interview – No One Joined": "KYC_Issue",
    "Missed Interview Email": "KYC_Issue",
    "Underage": "KYC_Issue",
    "Swift KYC Not Eligible": "KYC_Issue",
    "KYC Eligibility Inquiry": "KYC_Issue",
    "Fundednext Account Query": "Account Related Issue",
    "Did not receive Phase 2 Account": "Account Related Issue",
    "Facing error while trying to sign agreement": "Account Related Issue",
    "Challenge Account Query": "Account Related Issue",
    "Unable to Create an Account": "Account Related Issue",
    "Email already taken during registration": "Account Related Issue",
    "Cannot update information": "Account Related Issue",
    "Wrong Email Used": "Account Related Issue",
    "Email Change": "Account Related Issue",
    "Name Change": "Account Related Issue",
    "Country Change": "Account Related Issue",
    "Account Delete Request": "Account Related Issue",
    "Missing account in breached/inactive section": "Account Related Issue",
    "Account flagged without email": "Account Related Issue",
    "Account Deactivation Due to Abusive Activities": "Account Related Issue",
    "IP/Device Confirmation": "Account Related Issue",
    "Dashboard update delay": "Dashboard Related Issue",
    "Dashboard Access Blocked (Client Internet)": "Dashboard Related Issue",
    "Dashboard Access Blocked (TT Issue)": "Dashboard Related Issue",
    "Account Breach Issue": "Breach Issue",
    "“Undefined” Login Error": "Login_Issue",
    "Login Technical Glitch": "Login_Issue",
    "MT5 Platform Login Issues": "Login_Issue",
    "MT4 Login Issue": "Login_Issue",
    "TradingView login Issue": "Login_Issue",
    "Tradovate login Issue": "Login_Issue",
    "Ninjatrader login issue": "Login_Issue",
    "Competition Login Issue": "Login_Issue",
    "Missing Password Mail": "Password issue",
    "Next Phase Button Missing": "Next Phase Button Missing",
    "Platform Freeze": "Platform Issue",
    "Price/Chart Discrepancy": "Platform Issue",
    "Market Data Delayed Issue": "Platform Issue",
    "Missing Old Chart Data": "Platform Issue",
    "Unable to Use Indicator": "Platform Issue",
    "Unable to Use EA": "Platform Issue",
    "TradingView not available for CFD": "Platform Issue",
    "Crypto Pair Unavailable": "Platform Issue",
    "Crypto Weekend Trading": "Platform Issue",
    "High Spread": "Platform Issue",
    "Unable to Close During News": "Platform Issue",
    "Off-Market Hour Issue": "Platform Issue",
    "Incorrect Trading Cycle": "Trade Issue",
    "Trading Disabled": "Trade Issue",
    "Not Enough Money": "Trade Issue",
    "Pending Order Didn't Execute": "Trade Issue",
    "Trade Closed at Cycle End": "Trade Issue",
    "Trade Disappeared": "Trade Issue",
    "Unauthorized Trade": "Trade Issue",
    "TP Didn't Hit Desired Price": "Trade Issue",
    "Trade Closed Outside Candle (News)": "Trade Issue",
    "Profit Target Reached but Minimum Trading Days Incomplete": "Trade Issue",
    "Minimum Trading Days Confusion": "Trade Issue",
    "Weekend Gap": "Trade Issue",
    "ASK/BID Confusion": "Trade Issue",
    "50 Trades Limit Exceeded": "Trade Issue",
    "Slippage Issue": "Slippage",
    "Regular Slippage": "Slippage",
    "Due to High Lot Size": "Slippage",
    "During News / High Impact": "Slippage",
    "Due to Server Issue": "Slippage",
    "Volume Surge": "Slippage",
    "Midnight Slippage": "Slippage",
    "Swap Charge Confusion": "SWAP",
    "High Processing Fee Complaint": "Commission",
    "Affiliate Issue": "Commission",
    "Affiliate Code Failed": "Commission",
    "Payout On Hold": "Payout related issue",
    "Payout Delay Issue": "Payout related issue",
    "Not Eligible for Payout": "Payout related issue",
    "Payout Discrepancy": "Payout related issue",
    "Invalid Wallet": "Payout related issue",
    "RiseWorks Issue": "Payout related issue",
    "Unable to See Payout Proof": "Payout related issue",
    "Invoice Request": "Payout related issue",
    "TRM Deduction Email": "Payout related issue",
    "Payout from Breached Account": "Payout related issue",
    "Profit Share Below Minimum ($20)": "Payout related issue",
    "ECM Issue": "Payout related issue",
    "Claiming Brand Promise": "Payout related issue",
    "Payout Related Query": "Payout related issue",
    "Reported Late (3+ weeks)": "Payout related issue",
    "Elite Trader Certificate": "Certificate Issue",
    "Payout Certificate": "Certificate Issue",
    "Checking Elite Cert in Wrong Phase": "Certificate Issue",
    "Certificate Name Issue": "Certificate Issue",
    "Asking for Certificate After Phase 2": "Certificate Issue",
    "Leaderboard Error": "Competition Issue",
    "Unhappy with Winner Result": "Competition Issue",
    "Breached Competition Rule": "Competition Issue",
    "Reward Delay": "Competition Issue",
    "Asking Winners Info": "Competition Issue",
    "Registered for Next Month": "Competition Issue",
    "Wants Competition Reset": "Competition Issue",
    "Competition Rule Clarification": "Competition Issue",
    "Unable to register in the Monthly Competition": "Competition Issue",
    "Restricted Country Issue": "Restriction Related Issue",
    "Location Related Issue": "Restriction Related Issue",
    "Concern about EA Rules": "Restriction Related Issue",
    "EA Restriction (cTrader)": "Restriction Related Issue",
    "Abuser Client (Banned)": "Restriction Related Issue",
    "Leverage Reduction": "Restriction Related Issue",
    "Verdict from CPM": "Verdict from different team",
    "Verdict from Trading & Ethics": "Verdict from different team",
    "Verdict from PO": "Verdict from different team",
    "2FA Issue": "Tech Issue",
    "OTP Not Received": "Tech Issue",
    "Balance Mismatch": "Tech Issue",
    "Facing Payment Error": "Other Payment Issues",
    "Payment Method Not Available": "Other Payment Issues",
    "UPI Payment Missing": "Other Payment Issues",
    "Payment Rejected from Client’s End": "Other Payment Issues",
    "Partial Payment Not Possible": "Other Payment Issues",
    "No Payment Found (UPI/Local)": "Other Payment Issues",
    "Unable to Submit Payment Form (TC Pay)": "Other Payment Issues",
    "Account Not Provided Instantly (TC Pay)": "Other Payment Issues",
    "Account Not Provided Instantly (Local)": "Other Payment Issues",
    "Account Not Provided Instantly (Crypto)": "Other Payment Issues",
    "Paid Less Than Needed": "Other Payment Issues",
    "Crypto Payment Not Reflected": "Crypto Payment Isssue",
    "Wrong Network Payment": "Crypto Payment Isssue",
    "Network Not Available": "Crypto Payment Isssue",
    "Crypto Payment Failed (Client Side)": "Crypto Payment Isssue",
    "No Crypto Payment Found": "Crypto Payment Isssue",
    "Double Charged": "Card Payment issue",
    "Refund Delay": "Refund Related Issue",
    "Confirmo Refund Issue": "Refund Related Issue",
    "Coupon Code Not Working": "Coupon Code related issue",
    "Coupon Not Available": "Coupon Code related issue",
    "Forgot to Apply Coupon": "Coupon Code related issue",
    "Looking for coupon code": "Coupon Code related issue",
    "No Personal Coupon": "Coupon Code related issue",
    "Unhappy with Coupon Perks": "Discount related issue",
    "Unsatisfied with Discount": "Discount related issue",
    "Offer Related Query": "Offer Related Query",
    "Halloween Offer Query": "Offer Related Query",
    "Offer related confusion": "Offer Related Query",
    "Giveaway Claim": "Offer Related Query",
    "Giveaway Query": "Offer Related Query",
    "Unhappy Not Winning Giveaway": "Offer Related Query",
    "Missing Free BOGO Account": "Offer Related Query",
    "Asking for BOGO Early": "Offer Related Query",
    "Delay in Receiving Customer Support.": "Random Issues",
    "Subscription Email Issue": "Random Issues",
    "Dispute Related Issue": "Random Issues",
    "Other": "Random Issues",
    "VPS Usage and Replacement Inquiry": "Platform Issue",
    "VPS Change Inquiry": "Platform Issue",
    "Challenge Rule Clarification": "Competition Issue"
};

// Utilities for chart calculations
export const topNWithOther = (data, topN = 5) => {
    // ... logic if needed, or keeping it strictly for export
    return [];
};
export const calculatePercentages = () => { };
