CREATE TABLE IF NOT EXISTS "Intercom Report Feb14" (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    "conversation_id" text,
    "conversation_started_at" text,
    "conversation_created_at" text,
    "conversation_first_closed_at" text,
    "conversation_first_teammate_reply_at" text,
    "last_conversation_rating_updated_at" text,
    "channel" text,
    "last_teammate_rating" text,
    "last_teammate_rating_remark" text,
    "fin_ai_agent_rating" text,
    "fin_ai_agent_rating_remark" text,
    "current_conversation_state" text,
    "conversation_initiator_type" text,
    "conversation_tag_ids" text,
    "fin_ai_agent_participated" text,
    "agent_type" text,
    "conversation_first_response_time" text,
    "conversation_started_by" text,
    "currently_assigned_team_id" text,
    "currently_assigned_team_raw_id" text,
    "currently_assigned_teammate_id" text,
    "currently_assigned_teammate_raw_id" text,
    "reply_participant_teammate_ids" text,
    "last_rated_teammate_id" text,
    "last_rated_teammate_raw_id" text,
    "fin_ai_agent_resolution_state" text,
    "first_closing_teammate_id" text,
    "first_replying_teammate_id" text,
    "last_closing_teammate_id" text,
    "topics" text,
    "conversation_handling_time" text,
    "reassignments_count" text,
    "teammate_replies_count" text,
    "user_replies_count" text,
    "conversation_time_to_close" text,
    "time_to_first_close" text,
    "teammate_replies_to_close" text,
    "is_resolved_on_first_contact" text,
    "source_url" text,
    "conversation_title" text,
    "conversation_source" text,
    "conversation_last_closed_at" text,
    "conversation_updated_at" text,
    "conversation_priority" text,
    "fin_ai_agent_answer_coverage" text,
    "user_participant_names" text,
    "user_participant_ids" text,
    "user_participant_emails" text,
    "conversation_url" text,
    "user_location_continent_code" text,
    "user_location_country_code" text,
    "user_role" text,
    "user_name" text,
    "user_email" text,
    "user_id" text,
    "company_id" text,
    "company_name" text,
    "conversation_rating" text,
    "AI Topic" text,
    "AI Subtopic" text,
    "AI Issue summary" text,
    "Email" text,
    "Country" text,
    "Product Type" text,
    "Product type" text,
    "Ticket category" text,
    "Query Type" text
);
ALTER TABLE "Intercom Report Feb14" DISABLE ROW LEVEL SECURITY;